config/routes.rb
Rails.application.routes.draw do

  resources :skills

  resources :workers do
    collection do
      post "search"
    end
  end

  # Authentication
  devise_for :users

  # General

  # Root
  root 'workers#index'
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
  acts_as_taggable_on :skills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Authentication
  # before_action :authenticate_user!
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.page(params[:page])
  end

  def search
    respond_to do |format|
      format.json { render json: WorkersDatatable.new(view_context) }
    end
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:first_name, :last_name, :state, :city, :age, :salary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/application/_flash.html.erb
<%= bootstrap_flash %>

app/views/application/_footer.html.haml
%footer.footer
  .container
    %p.text-muted.text-center
      《Rails 实践》
      = link_to "http://rails-practice.com/", "http://rails-practice.com/", target: "_blank"

app/views/application/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Demo", root_path, class: "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Workers", workers_path %></li>
        <li><%= link_to "Skills", skills_path %></li>
      </ul>
      <%= form_tag(workers_path, method: :get, class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= search_field_tag "tag", params["tag"], class: "form-control input-sm search-form", placeholder: "workers name" %>
        </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "退出", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "登录", new_user_session_path %></li>
          <li><%= link_to "注册", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/application/_sider.html.erb
<div class="well sidebar-nav">
  <h3>Sidebar</h3>
  <ul class="nav nav-list">
    <li class="nav-header">Sidebar</li>
  </ul>
  <%= image_tag("logo.png") %>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Demo" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

</head>
<body>
<%= render "navbar" %>
<div class="container">
  <%= render "flash" %>
  <%= yield %>
</div> <!-- /container -->
<%= render "footer" %>
<%= yield(:page_modal) if content_for?(:page_modal) %>
<%= javascript_include_tag "application" %>
<%= yield(:page_javascript) if content_for?(:page_javascript) %>
</body>
</html>

app/views/shared/_intro.html.erb
<div class="jumbotron">
  <h3>《Rails 实践》</h3>
  <p>本课程面向初次使用 Rails 的开发人员，讲解如何使用 Rails 框架开发 web 项目。 同时，我也会分享 Rails 开发过程中的实践经验。在本课程讲解的过程中，我会带领大家，一同编写一个在线网店程序。最后，我们还将要把这个网店程序，在云服务器上部署、运行。</p>
  <p><a class="btn btn-primary btn-lg" href="http://rails-practice.com/" target="_blank">查看教程（网页版）</a></p>
</div>

app/views/skills/_form.html.erb
<%= form_for @skill, :html => { :class => "form-horizontal skill" } do |f| %>

    <% if @skill.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @skill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@skill[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            skills_path, :class => 'btn btn-default' %>

<% end %>

app/views/skills/edit.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/skills/index.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= link_to skill.name, skill_path(skill) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_skill_path(skill), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      skill_path(skill),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_skill_path,
            :class => 'btn btn-primary' %>

app/views/skills/new.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/skills/show.html.erb
<%- model_class = Skill -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @skill.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              skills_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_skill_path(@skill), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              skill_path(@skill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/workers/_form.html.erb
<%= form_for @worker, :html => { :class => "form-horizontal worker" } do |f| %>

    <% if @worker.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @worker.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:first_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:last_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:state]) %>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:city]) %>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:age]) %>
  </div>
  <div class="control-group">
    <%= f.label :salary, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :salary, :class => 'form-control' %>
    </div>
    <%= error_span(@worker[:salary]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            workers_path, :class => 'btn btn-default' %>

<% end %>

app/views/workers/edit.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workers/index.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_worker_path, :class => 'btn btn-primary pull-right' %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<div class="row">
  <form id="skill_form">
    <% Skill.all.each do |skill| %>
      <div class="col-xs-6 col-md-2">
        <label class="radio-inline">
          <input type="checkbox" name="skill" id="skill_<%= skill.id %>" class="skill" value="<%= skill.name %>"> <%= skill.name %>
        </label>
      </div>
    <% end %>
  </form>
</div>

<hr />

<table class="table table-striped datatable" id="data" data-source="<%= search_workers_url(format: "json") %>">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:salary) %></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/workers/new.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workers/show.html.erb
<%- model_class = Worker -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @worker.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @worker.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @worker.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @worker.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @worker.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salary) %>:</strong></dt>
  <dd><%= @worker.salary %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              workers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_worker_path(@worker), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              worker_path(@worker),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>